// Initialize the dropdowns on page load
document.addEventListener('DOMContentLoaded', () => {
    populateProvincesPermanent();
});

// Sample data structure for provinces and their cities
const provinces = {
    "Abra": {
        cities: [
            "Bangued",
            "Boliney",
            "Bucay",
            "Bucloc",
            "Daguioman",
            "Danglas",
            "Dolores",
            "La Paz",
            "Lacub",
            "Lagangilang",
            "Lagayan",
            "Langiden",
            "Licuan-Baay",
            "Luba",
            "Malibcong",
            "Manabo",
            "Peñarrubia",
            "Pidigan",
            "Pilar",
            "Sallapadan",
            "San Isidro",
            "San Juan",
            "San Quintin",
            "Tayum",
            "Tineg",
            "Villaviciosa"
        ]
    },
    "Agusan del Sur": {
        cities: [
            "Bayugan",
            "Bunawan",
            "Esperanza",
            "La Paz",
            "Loreto",
            "Proseperidad",
            "Rosario",
            "San Francisco",
            "San Luis",
            "Santa Josefa",
            "Sibagat",
            "Talacogon",
            "Trento",
            "Veruela"
        ]
    },
    "Aklan": {
        cities: [
            "Altavas",
            "Balete",
            "Banga",
            "Batan",
            "Buruanga",
            "Ibajay",
            "Kalibo",
            "Lezo",
            "Libacao",
            "Madalag",
            "Makato",
            "Malay",
            "Malinao",
            "Nabas",
            "New Washington",
            "Numancia",
            "Tangalan"
        ]
    },
    "Albay": {
        cities: [
            "Bacacay",
            "Camalig",
            "Daraga",
            "Guinobatan",
            "Jovellar",
            "Legazpi",
            "Libon",
            "Ligao",
            "Malilipot",
            "Malinao",
            "Manito",
            "Oas",
            "Pio Duran",
            "Polangui",
            "Rapu-Rapu",
            "Santo Domingo",
            "Tabaco",
            "Tiwi"
        ]
    },
    "Antique": {
        cities: [
            "Anini-y",
            "Barbaza",
            "Belison",
            "Bugasong",
            "Caluya",
            "Culasi",
            "Hamtic",
            "Laua-an",
            "Libertad",
            "Pandan",
            "Patnongon",
            "San Jose de Buenavista",
            "San Remigio",
            "Sebaste",
            "Tibiao",
            "Tobias Fornier",
            "Valderrama"
        ]
    },
    "Apayao": {
        cities: [
            "Calanasan",
            "Conner",
            "Flora",
            "Kabugao",
            "Luna",
            "Pudtol",
            "Santa Marcela"
        ]
    },
    "Aurora": {
        cities: [
            "Baler",
            "Casiguran",
            "Dilasag",
            "Dinalungan",
            "Dingalan",
            "Dipaculao",
            "Maria Aurora",
            "San Luis"
        ]
    },
    "Basilan": {
        cities: [
            "Akbar",
            "Al-Barka",
            "Hadji Mohammad Ajul",
            "Hadji Muhtamad",
            "Isabela City",
            "Lamitan",
            "Lantawan",
            "Maluso",
            "Sumisip",
            "Tabuan-Lasa",
            "Tipo-Tipo",
            "Tuburan",
            "Ungkaya Pukan"
        ]
    },
    "Bataan": {
        cities: [
            "Abucay",
            "Bagac",
            "Balanga",
            "Dinalupihan",
            "Hermosa",
            "Limay",
            "Mariveles",
            "Morong",
            "Orani",
            "Orion",
            "Pilar",
            "Samal"
        ]
    },
    "Batanes": {
        cities: [
            "Basco",
            "Itbayat",
            "Ivana",
            "Mahatao",
            "Sabtang",
            "Uyugan"
        ]
    },
    "Batangas": {
        cities: [
            "Agoncillo",
            "Alitagtag",
            "Balayan",
            "Bocaue",
            "Bulakan",
            "Bustos",
            "Calumpit",
            "Doña Remedios Trinidad",
            "Guiguinto",
            "Hagonoy",
            "Malolos",
            "Marilao",
            "Meycauayan",
            "Norzagaray",
            "Obando",
            "Pandi",
            "Paombong",
            "Plaridel",
            "Pulilan",
            "San Ildefonso",
            "San Jose del Monte",
            "San Miguel",
            "San Rafael",
            "Santa Maria"
        ]
    },
    "Benguet": {
        cities: [
            "Atok",
            "Bakun",
            "Bokod",
            "Buguias",
            "Itogon",
            "Kabayan",
            "Kapangan",
            "Kibungan",
            "La Trinidad",
            "Mankayan",
            "Sablan",
            "Tuba",
            "Tublay"
        ]
    },
    "Biliran": {
        cities: [
            "Almeria",
            "Biliran",
            "Cabucgayan",
            "Caibiran",
            "Culaba",
            "Kawayan",
            "Maripipi",
            "Naval"
        ]
    },
    "Bohol": {
        cities: [
            "Alburquerque",
            "Alicia",
            "Anda",
            "Antequera",
            "Baclayon",
            "Balilihan",
            "Batuan",
            "Bien Unido",
            "Bilar",
            "Buenavista",
            "Calape",
            "Candijay",
            "Carmen",
            "Catigbian",
            "Clarin",
            "Corella",
            "Cortes",
            "Dagohoy",
            "Danao",
            "Dauis",
            "Dimiao",
            "Duero",
            "Garcia Hernandez",
            "Getafe",
            "Guindulman",
            "Inabanga",
            "Jagna",
            "Lila",
            "Loay",
            "Loboc",
            "Loon",
            "Mabini",
            "Maribojoc",
            "Panglao",
            "Pilar",
            "President Carlos P. Garcia",
            "Sagbayan",
            "San Isidro",
            "San Miguel",
            "Sevilla",
            "Sierra Bullones",
            "Sikatuna",
            "Tagbilaran",
            "Talibon",
            "Trinidad",
            "Tubigon",
            "Ubay",
            "Valencia"
        ]
    },
    "Bukidnon": {
        cities: [
            "Baungon",
            "Cabanglasan",
            "Damulog",
            "Dangcagan",
            "Don Carlos",
            "Impasugong",
            "Kadingilan",
            "Kalilangan",
            "Kibawe",
            "Kitaotao",
            "Lantapan",
            "Libona",
            "Malaybalay",
            "Malitbog",
            "Manolo Fortich",
            "Maramag",
            "Pangantucan",
            "Quezon",
            "San Fernando",
            "Sumilao",
            "Talakag",
            "Valencia"
        ]
    },
    "Bulacan": {
        cities: [
            "Angat",
            "Balagtas",
            "Baliuag",
            "Bocaue",
            "Bulakan",
            "Bustos",
            "Calumpit",
            "Doña Remedios Trinidad",
            "Guiguinto",
            "Hagonoy",
            "Malolos",
            "Marilao",
            "Meycauayan",
            "Norzagaray",
            "Obando",
            "Pandi",
            "Paombong",
            "Plaridel",
            "Pulilan",
            "San Ildefonso",
            "San Jose del Monte",
            "San Miguel",
            "San Rafael",
            "Santa Maria"
        ]
    },
    "Cagayan": {
        cities: [
            "Abulug",
            "Alcala",
            "Allacapan",
            "Amulung",
            "Aparri",
            "Baggao",
            "Ballesteros",
            "Buguey",
            "Calayan",
            "Camalaniugan",
            "Claveria",
            "Enrile",
            "Gattaran",
            "Gonzaga",
            "Iguig",
            "Lal-lo",
            "Lasam",
            "Pamplona",
            "Pasacao",
            "Pili",
            "Presentacion",
            "Ragay",
            "Sagñay",
            "San Fernando",
            "San Jose",
            "Sipocot",
            "Tuao",
            "Tuguegarao"
        ]
    },
    "Camarines Norte": {
        cities: [
            "Basud",
            "Capalonga",
            "Daet",
            "Jose Panganiban",
            "Labo",
            "Mercedes",
            "Paracale",
            "San Lorenzo Ruiz",
            "San Vicente",
            "Santa Elena",
            "Talisay",
            "Vinzons"
        ]
    },
    "Camarines Sur": {
        cities: [
            "Baao",
            "Balatan",
            "Bato",
            "Bombon",
            "Buhi",
            "Bula",
            "Cabusao",
            "Calabanga",
            "Camaligan",
            "Canaman",
            "Caramoan",
            "Del Gallego",
            "Gainza",
            "Garchitorena",
            "Goa",
            "Iriga",
            "Lagonoy",
            "Libmanan",
            "Lupi",
            "Magarao",
            "Milaor",
            "Minalabac",
            "Nabua",
            "Naga",
            "Ocampo",
            "Pamplona",
            "Pasacao",
            "Pili",
            "Presentacion",
            "Ragay",
            "Sagñay",
            "San Fernando",
            "San Jose",
            "Sipocot",
            "Siruma",
            "Tigaon",
            "Tinambac"
        ]
    },
    "Camiguin": {
        cities: [
            "Catarman",
            "Guinsiliban",
            "Mahinog",
            "Mambajao",
            "Sagay"
        ]
    },
    "Capiz": {
        "cities": [
            "Cuartero",
            "Dao",
            "Dumalag",
            "Dumarao",
            "Ivisan",
            "Jamindan",
            "Maayon",
            "Mambusao",
            "Panay",
            "Panitan",
            "Pilar",
            "Pontevedra",
            "President Roxas",
            "Roxas City",
            "Sapian",
            "Sigma",
            "Tapaz"
        ]
    },
    "Catanduanes": {
        "cities": [
            "Bagamanoc",
            "Baras",
            "Bato",
            "Caramoran",
            "Gigmoto",
            "Pandan",
            "Panganiban",
            "San Andres",
            "San Miguel",
            "Viga",
            "Virac"
        ]
    },
    "Cavite": {
        "cities": [
            "Alfonso",
            "Amadeo",
            "Bacoor",
            "Carmona",
            "Cavite City",
            "Dasmariñas",
            "General Emilio Aguinaldo",
            "General Mariano Alvarez",
            "General Trias",
            "Imus",
            "Indang",
            "Kawit",
            "Magallanes",
            "Maragondon",
            "Mendez",
            "Naic",
            "Noveleta",
            "Rosario",
            "Silang",
            "Tagaytay",
            "Tanza",
            "Ternate",
            "Trece Martires"
        ]
    },
    "Cebu": {
        "cities": [
            "Bagamanoc",
            "Baras",
            "Bato",
            "Caramoran",
            "Gigmoto",
            "Pandan",
            "Panganiban",
            "San Andres",
            "San Miguel",
            "Viga",
            "Virac"
        ]
    },
    "Cotobato": {
        "cities": [
            "Alamada",
            "Aleosan",
            "Antipas",
            "Arakan",
            "Banisilan",
            "Carmen",
            "Kabacan",
            "Kidapawan",
            "Libungan",
            "M'lang",
            "Magpet",
            "Makilala",
            "Matalam",
            "Midsayap",
            "Pigcawayan",
            "Pikit",
            "President Roxas",
            "Tulunan"
        ]
    },
    "Davao de Oro": {
        "cities": [
            "Compostela",
            "Laak",
            "Mabini",
            "Maco",
            "Maragusan",
            "Mawab",
            "Monkayo",
            "Montevista",
            "Nabunturan",
            "New Bataan",
            "Pantukan"
        ]
    },
    "Davao del Norte": {
        "cities": [
            "Asuncion",
            "Braulio E. Dujali",
            "Carmen",
            "Kapalong",
            "New Corella",
            "Panabo",
            "Samal",
            "San Isidro",
            "Santo Tomas",
            "Tagum",
            "Talaingod"
        ]
    },
    "Davao del Sur": {
        "cities": [
            "Bansalan",
            "Digos",
            "Hagonoy",
            "Kiblawan",
            "Magsaysay",
            "Matanao",
            "Padada",
            "Santa Cruz",
            "Sulop"
        ]
    },
    "Davao Occidental": {
        "cities": [
            "Don Marcelino",
            "Jose Abad Santos",
            "Malita",
            "Santa Maria",
            "Sarangani"
        ]
    },
    "Davao Oriental": {
        "cities": [
            "Baganga",
            "Banaybanay",
            "Boston",
            "Caraga",
            "Cateel",
            "Governor Generoso",
            "Lupon",
            "Manay",
            "Mati",
            "San Isidro",
            "Tarragona"
        ]
    },
    "Dinagat Islands": {
        "cities": [
            "Basilisa",
            "Cagdianao",
            "Dinagat",
            "Libjo",
            "Loreto",
            "San Jose",
            "Tubajon"
        ]
    },
    "Eastern Samar": {
        "cities": [
            "Arteche",
            "Balangiga",
            "Balangkayan",
            "Borongan",
            "Can-avid",
            "Dolores",
            "General MacArthur",
            "Giporlos",
            "Guiuan",
            "Hernani",
            "Jipapad",
            "Lawaan",
            "Llorente",
            "Maslog",
            "Maydolong",
            "Mercedes",
            "Oras",
            "Quinapondan",
            "Salcedo",
            "San Julian",
            "San Lorenzo",
            "Sulat",
            "Taft"
        ]
    },
    "Guimaras": {
        "cities": [
            "Buenavista",
            "Jordan",
            "Nueva Valencia",
            "San Lorenzo",
            "Sibunag"
        ]
    },
    "Ifugao": {
        "cities": [
            "Aguinaldo",
            "Alfonso Lista",
            "Asipulo",
            "Banaue",
            "Hingyon",
            "Hungduan",
            "Kiangan",
            "Lagawe",
            "Lamut",
            "Mayoyao",
            "Tinoc"
        ]
    },
    "Ilocos Norte": {
        "cities": [
            "Adams",
            "Bacarra",
            "Badoc",
            "Bangui",
            "Banna",
            "Batac",
            "Burgos",
            "Carasi",
            "Currimao",
            "Dingras",
            "Dumalneg",
            "Laoag",
            "Marcos",
            "Nueva Era",
            "Pagudpud",
            "Paoay",
            "Pasuquin",
            "Piddig",
            "Pinili",
            "San Nicolas",
            "Sarrat",
            "Solsona",
            "Vintar"
        ]
    },
    "Ilocos Sur": {
        "cities": [
            "Alilem",
            "Banayoyo",
            "Bantay",
            "Burgos",
            "Cabugao",
            "Candon",
            "Caoayan",
            "Cervantes",
            "Galimuyod",
            "Gregorio del Pilar",
            "Lidlidda",
            "Magsingal",
            "Nagbukel",
            "Narvacan",
            "Quirino",
            "Salcedo",
            "San Emilio",
            "San Esteban",
            "San Ildefonso",
            "San Juan",
            "San Vicente",
            "Santa",
            "Santa Catalina",
            "Santa Cruz",
            "Santa Lucia",
            "Santa Maria",
            "Santiago",
            "Santo Domingo",
            "Sigay",
            "Sinait",
            "Sugpon",
            "Tigbauan",
            "Tagudin",
            "Vigan"
        ]
    },
    "Iloilo": {
        "cities": [
            "Ajuy",
            "Alimodian",
            "Anilao",
            "Badiangan",
            "Balasan",
            "Banate",
            "Barotac Nuevo",
            "Barotac Viejo",
            "Batad",
            "Bingawan",
            "Cabatuan",
            "Calinog",
            "Carles",
            "Concepcion",
            "Dingle",
            "Dueñas",
            "Dumangas",
            "Estancia",
            "Guimbal",
            "Igbaras",
            "Janiuay",
            "Lambunao",
            "Leganes",
            "Lemery",
            "Leon",
            "Maasin",
            "Mina",
            "New Lucena",
            "Oton",
            "Passi",
            "Pavia",
            "Pototan",
            "San Dionisio",
            "San Enrique",
            "San Joaquin",
            "San Miguel",
            "San Rafael",
            "Santa Barbara",
            "Sara",
            "Tigbauan",
            "Tubungan",
            "Zarraga"
        ]
    },
    "Isabela": {
        "cities": [
            "Alicia",
            "Angadanan",
            "Aurora",
            "Benito Soliven",
            "Burgos",
            "Cabagan",
            "Cabatuan",
            "Cauayan",
            "Cordon",
            "Delfin Albano",
            "Dinapigue",
            "Divilacan",
            "Echague",
            "Gamu",
            "Ilagan",
            "Jones",
            "Luna",
            "Maconacon",
            "Mallig",
            "Naguilian",
            "Palanan",
            "Quezon",
            "Quirino",
            "Ramon",
            "Reina Mercedes",
            "Roxas",
            "San Agustin",
            "San Guillermo",
            "San Isidro",
            "San Manuel",
            "San Mariano",
            "San Mateo",
            "San Pablo",
            "Santa Maria",
            "Santiago",
            "Santo Tomas",
            "Tumauini"
        ]
    },
    "Kalinga": {
        "cities": [
            "Balbalan",
            "Lubuagan",
            "Pasil",
            "Pinukpuk",
            "Rizal",
            "Tabuk",
            "Tanudan",
            "Tinglayan"
        ]
    },
    "La Union": {
        "cities": [
            "Agoo",
            "Aringay",
            "Bacnotan",
            "Bagulin",
            "Balaoan",
            "Bangar",
            "Bauang",
            "Burgos",
            "Caba",
            "Luna",
            "Naguilian",
            "Pugo",
            "Rosario",
            "San Fernando",
            "San Gabriel",
            "San Juan",
            "Santo Tomas",
            "Santol",
            "Sudipen",
            "Tubao"
        ]
    },
    "Laguna": {
        "cities": [
            "Alaminos",
            "Bay",
            "Biñan",
            "Cabuyao",
            "Calamba",
            "Calauan",
            "Cavinti",
            "Famy",
            "Kalayaan",
            "Liliw",
            "Los Baños",
            "Luisiana",
            "Lumban",
            "Mabitac",
            "Magdalena",
            "Majayjay",
            "Nagcarlan",
            "Paete",
            "Pagsanjan",
            "Pakil",
            "Pangil",
            "Pila",
            "Rizal",
            "San Pablo",
            "San Pedro",
            "Santa Cruz",
            "Santa Maria",
            "Santiago",
            "Santo Tomas",
            "Tumauini"
        ]
    },
    "Lanao Del Norte": {
        "cities": [
            "Bacolod",
            "Baloi",
            "Baroy",
            "Iligan City",
            "Kapatagan",
            "Sultan Naga Dimaporo (Karomatan)",
            "Kauswagan",
            "Kolambugan",
            "Lala",
            "Linamon",
            "Magsaysay",
            "Maigo",
            "Matungao",
            "Munai",
            "Nunungan",
            "Pantao Ragat",
            "Tagoloan",
            "Tubod"
        ]
    },
    "Lanao Del Sur": {
        "cities": [
            "Bacolod Kalawi",
            "Balabagan",
            "Balindong",
            "Bayang",
            "Binidayan",
            "Bubong",
            "Butig",
            "Ganassi",
            "Kapai",
            "Lumba-Bayabao",
            "Lumbatan",
            "Madalum",
            "Madamba",
            "Marawi",
            "Malilit",
            "Marantao",
            "Picong",
            "Poblacion",
            "Ranao",
            "Sabalan",
            "Tubod",
            "Tugaya"
        ]
    },
    "Leyte": {
        "cities": [
            "Abuyog",
            "Alangalang",
            "Albuera",
            "Babatngon",
            "Barugo",
            "Bato",
            "Baybay",
            "Burauen",
            "Calubian",
            "Capoocan",
            "Carigara",
            "Dagami",
            "Hindang",
            "Inopacan",
            "Isabel",
            "Jaro",
            "Javier",
            "Julita",
            "Kananga",
            "La Paz",
            "Leyte",
            "MacArthur",
            "Mahaplag",
            "Matag-ob",
            "Matalom",
            "Mayorga",
            "Merida",
            "Ormoc",
            "Palo",
            "Palompon",
            "Pastrana",
            "San Isidro",
            "San Miguel",
            "Santa Fe",
            "Santa Cruz",
            "Tacloban",
            "Tanauan",
            "Tolosa",
            "Tunga",
            "Villaba"
        ]
    },
    "Maguindanao": {
        "cities": [
            "Ampatuan",
            "Barira",
            "Buldon",
            "Buluan",
            "Cotabato City",
            "Datu Abdullah Sangki",
            "Datu Anggal Midtimbang",
            "Datu Blah T. Sinsuat",
            "Datu Hoffer Ampatuan",
            "Datu Montawal",
            "Datu Odin Sinsuat",
            "Datu Paglas",
            "Datu Piang",
            "Datu Salibo",
            "Datu Saudi-Ampatuan",
            "Datu Unsay",
            "General Salipada K. Pendatun",
            "Guindulungan",
            "Kabuntalan",
            "Mamasapano",
            "Mangudadatu",
            "Matanog",
            "Northern Kabuntalan",
            "Pagalungan",
            "Paglat",
            "Shariff Aguak",
            "Sultan Kudarat",
            "Sultan Mastura",
            "Talayan",
            "Upi"
        ]
    },
    "Marinduque": {
        "cities": [
            "Boac",
            "Buenavista",
            "Gasan",
            "Mogpog",
            "Santa Cruz",
            "Torrijos"
        ]
    },
    "Masbate": {
        "cities": [
            "Aroroy",
            "Baleno",
            "Balud",
            "Batuan",
            "Cataingan",
            "Cawayan",
            "Claveria",
            "Dimasalang",
            "Esperanza",
            "Mandaon",
            "Masbate City",
            "Milagros",
            "Mobo",
            "Monreal",
            "Palanas",
            "Pio V. Corpuz",
            "Placer",
            "San Fernando",
            "San Jacinto",
            "San Pascual",
            "Uson"
        ]
    },
    "Misamis Occidental": {
        "cities": [
            "Aloran",
            "Baliangao",
            "Bonifacio",
            "Calamba",
            "Clarin",
            "Concepcion",
            "Don Victoriano Chiongbian",
            "Jimenez",
            "Lopez Jaena",
            "Oroquieta",
            "Ozamiz",
            "Panaon",
            "Plaridel",
            "Sapang Dalaga",
            "Sinacaban",
            "Tangub",
            "Tudela"
        ]
    },
    "Misamis Oriental": {
        "cities": [
            "Alubijid",
            "Balingasag",
            "Balingoan",
            "Binuangan",
            "Claveria",
            "El Salvador",
            "Gingoog",
            "Gitagum",
            "Initao",
            "Jasaan",
            "Kinoguitan",
            "Lagonglong",
            "Laguindingan",
            "Libertad",
            "Lugait",
            "Magsaysay",
            "Manticao",
            "Medina",
            "Naawan",
            "Opol",
            "Salay",
            "Sugbongcogon",
            "Tagoloan",
            "Talisayan",
            "Villanueva"
        ]
    },
    "Mountain Province": {
        "cities": [
            "Barlig",
            "Bauko",
            "Besao",
            "Bontoc",
            "Natonin",
            "Paracelis",
            "Sabangan",
            "Sadanga",
            "Sagada",
            "Tadian"
        ]
    },
    "Negros Occidental": {
        "cities": [
            "Bago",
            "Binalbagan",
            "Cadiz",
            "Calatrava",
            "Candoni",
            "Cauayan",
            "Enrique B. Magalona",
            "Escalante",
            "Himamaylan",
            "Hinigaran",
            "Hinoba-an",
            "Ilog",
            "Isabela",
            "Kabankalan",
            "La Carlota",
            "La Castellana",
            "Manapla",
            "Moises Padilla",
            "Murcia",
            "Negros Occidental",
            "Pulupandan",
            "San Carlos",
            "San Enrique",
            "Silay",
            "Sipalay",
            "Talisay",
            "Victorias"
        ]
    },
    "Negros Oriental": {
        "cities": [
            "Amlan",
            "Ayungon",
            "Bacong",
            "Bais",
            "Basay",
            "Bayawan",
            "Bindoy",
            "Canlaon",
            "Dauin",
            "Dumaguete",
            "Guihulngan",
            "Gamay",
            "Laoang",
            "Lapinig",
            "Las Navas",
            "Lope de Vega",
            "Mapanas",
            "Mondragon",
            "Palapag",
            "Pambujan",
            "San Antonio",
            "San Isidro",
            "San Jose",
            "San Vicente",
            "Silvino Lobos",
            "Valencia",
            "Vallehermoso",
            "Zamboanguita"
        ]
    },
    "Northern Samar": {
        "cities": [
            "Allen",
            "Biri",
            "Bobon",
            "Capul",
            "Catarman",
            "Catubig",
            "Gamay",
            "Laoang",
            "Lapinig",
            "Las Navas",
            "Lope de Vega",
            "Mapanas",
            "Mondragon",
            "Palapag",
            "Pambujan",
            "San Antonio",
            "San Isidro",
            "San Jose",
            "San Vicente",
            "Silvino Lobos",
            "Victoria"
        ]
    },
    "Nueva Ecija": {
        "cities": [
            "Aliaga",
            "Bongabon",
            "Cabanatuan",
            "Cabiao",
            "Carranglan",
            "Cuyapo",
            "Gabaldon",
            "General Mamerto Natividad",
            "General Tinio",
            "Guimba",
            "Jaen",
            "Nampicuan",
            "Palayan City",
            "Peñaranda",
            "San Antonio",
            "San Isidro",
            "San Leonardo",
            "San Jose City",
            "Sto. Domingo",
            "Talavera",
            "Zaragoza"
        ]
    },
    "Nueva Vizcaya": {
        "cities": [
            "Alfonso Castañeda",
            "Ambaguio",
            "Aritao",
            "Bagabag",
            "Bambang",
            "Bayombong",
            "Diadi",
            "Dupax del Norte",
            "Dupax del Sur",
            "Kasibu",
            "Kayapa",
            "Quezon",
            "Santa Fe",
            "Solano",
            "Villaverde"
        ]
    },
    "Occidental Mindoro": {
        "cities": [
            "Abra de Ilog",
            "Calintaan",
            "Looc",
            "Lubang",
            "Magsaysay",
            "Mamburao",
            "Paluan",
            "Rizal",
            "Sablayan",
            "San Jose",
            "Santa Cruz"
        ]
    },
    "Oriental Mindoro": {
        "cities": [
            "Baco",
            "Bansud",
            "Bongabong",
            "Bulalacao",
            "Calapan",
            "Gloria",
            "Mansalay",
            "Naujan",
            "Pinamalayan",
            "Pola",
            "Puerto Galera",
            "Roxas",
            "San Teodoro",
            "Socorro",
            "Victoria"
        ]
    },
    "Palawan": {
        "cities": [
            "Aborlan",
            "Agutaya",
            "Araceli",
            "Balabac",
            "Bataraza",
            "Brooke's Point",
            "Busuanga",
            "Cagayancillo",
            "Coron",
            "Culion",
            "Cuyo",
            "Dumaran",
            "El Nido",
            "Kalayaan",
            "Linapacan",
            "Magsaysay",
            "Narra",
            "Puerto Princesa",
            "Quezon",
            "Rizal",
            "Roxas",
            "San Vicente",
            "Sofronio Española",
            "Taytay"
        ]
    },
    "Pampanga": {
        "cities": [
            "Apalit",
            "Arayat",
            "Bacolor",
            "Candaba",
            "Floridablanca",
            "Guagua",
            "Lubao",
            "Mabalacat",
            "Macabebe",
            "Magalang",
            "Masantol",
            "Mexico",
            "Malasiqui",
            "Binalonan",
            "Bayambang",
            "Bani"
        ]
    },
    "Pangasinan": {
        "cities": [
            "Agno",
            "Aguilar",
            "Alaminos",
            "Anda",
            "Asingan",
            "Balungao",
            "Bani",
            "Bugallon",
            "Burgos",
            "Calasiao",
            "Dagupan",
            "Dasol",
            "Infanta",
            "Labrador",
            "Laoac",
            "Lingayen",
            "Mabini",
            "Malasiqui",
            "Mangaldan",
            "Mangatarem",
            "Mapandan",
            "Natividad",
            "Pozorrubio",
            "Rosales",
            "San Carlos",
            "San Fabian",
            "San Jacinto",
            "San Manuel",
            "San Nicolas",
            "San Quintin",
            "Santa Barbara",
            "Santa Maria",
            "Santo Tomas",
            "Sison",
            "Sual",
            "Tayug",
            "Umingan",
            "Mapandan"
        ]
    },
    "Nueva Ecija": {
        "cities": [
            "Aliaga",
            "Bongabon",
            "Cabanatuan",
            "Cabiao",
            "Carranglan",
            "Cuyapo",
            "Gabaldon",
            "General Mamerto Natividad",
            "General Tinio",
            "Guimba",
            "Jaen",
            "Nampicuan",
            "Palayan City",
            "Peñaranda",
            "San Antonio",
            "San Isidro",
            "San Leonardo",
            "San Jose City",
            "Sto. Domingo",
            "Talavera",
            "Zaragoza"
        ]
    },
    "Quezon": {
        "cities": [
            "Agdangan",
            "Alabat",
            "Atimonan",
            "Buenavista",
            "Burdeos",
            "Calauag",
            "Candelaria",
            "Catanauan",
            "Dolores",
            "General Luna",
            "General Nakar",
            "Guinayangan",
            "Infanta",
            "Jomalig",
            "Lopez",
            "Lucban",
            "Mauban",
            "Pagbilao",
            "Pangil",
            "Patnanungan",
            "Plaridel",
            "Quezon",
            "Sampaloc",
            "San Antonio",
            "San Francisco",
            "San Narciso",
            "Sariaya",
            "Tiaong",
            "Unisan"
        ]
    },
    "Quirino": {
        "cities": [
            "Aglipay",
            "Cabarroguis",
            "Diffun",
            "Maddela",
            "Nagtipunan",
            "Saguday"
        ]
    },
    "Rizal": {
        "cities": [
            "Angono",
            "Antipolo",
            "Baras",
            "Binangonan",
            "Cainta",
            "Cardona",
            "Jalajala",
            "Morong",
            "Pililla",
            "Rodriguez",
            "San Mateo",
            "Tanay",
            "Taytay",
            "Teresa"
        ]
    },
    "Romblon": {
        "cities": [
            "Alcantara",
            "Banton",
            "Cajidiocan",
            "Calatrava",
            "Concepcion",
            "Corcuera",
            "Ferrol",
            "Looc",
            "Magdiwang",
            "Odiongan",
            "Romblon",
            "San Agustin",
            "San Andres",
            "San Fernando",
            "San Jose",
            "Santa Fe",
            "Santa Maria"
        ]
    },
    "Samar": {
        "cities": [
            "Almagro",
            "Basey",
            "Calbayog",
            "Calbiga",
            "Catbalogan",
            "Daram",
            "Gandara",
            "Matuguinao",
            "San Jorge",
            "San Jose de Buan",
            "San Miguel",
            "San Sebastian",
            "Silvino Lobos",
            "Villareal",
            "Zumarraga"
        ]
    },
    "Sarangani": {
        "cities": [
            "Alabel",
            "Glan",
            "Kiamba",
            "Maasim",
            "Maitum",
            "Malapatan",
            "Malungon"
        ]
    },
    "Siquijor": {
        "cities": [
            "Enrique Villanueva",
            "Larena",
            "Lazi",
            "Maria",
            "San Juan",
            "Siquijor"
        ]
    },
    "Sorsogon": {
        "cities": [
            "Barcelona",
            "Bulan",
            "Bulusan",
            "Casiguran",
            "Castilla",
            "Donsol",
            "Gubat",
            "Irosin",
            "Juban",
            "Magallanes",
            "Matnog",
            "Pilar",
            "Prieto Diaz",
            "Santa Magdalena",
            "Sorsogon City"
        ]
    },
    "South Cotabato": {
        "cities": [
            "Banga",
            "General Santos",
            "Koronadal",
            "Lake Sebu",
            "Norala",
            "Polomolok",
            "Santo Niño",
            "Surallah",
            "Tampakan",
            "Tantangan",
            "T'Boli",
            "Tupi"
        ]
    },
    "Southern Leyte": {
        "cities": [
            "Anahawan",
            "Bontoc",
            "Hinunangan",
            "Hinundayan",
            "Libagon",
            "Liloan",
            "Limasawa",
            "Maasin",
            "Macrohon",
            "Malitbog",
            "Padre Burgos",
            "Pintuyan",
            "Saint Bernard",
            "San Francisco",
            "San Juan",
            "San Ricardo",
            "Silago",
            "Sogod",
            "Tomas Oppus"
        ]
    },
    "Sultan Kudarat": {
        "cities": [
            "Bagumbayan",
            "Columbio",
            "Esperanza",
            "Isulan",
            "Kalamansig",
            "Lambayong",
            "Lebak",
            "Lutayan",
            "Palimbang",
            "President Quirino",
            "Senator Ninoy Aquino",
            "Tacurong"
        ]
    },
    "Sulu": {
        "cities": [
            "Banguingui",
            "Hadji Panglima Tahil",
            "Indanan",
            "Jolo",
            "Kalingalan Caluang",
            "Lugus",
            "Luuk",
            "Maimbung",
            "Old Panamao",
            "Omar",
            "Pandami",
            "Panglima Estino",
            "Pangutaran",
            "Parang",
            "Pata",
            "Patikul",
            "Siasi",
            "Talipao",
            "Tapul"
        ]
    },
    "Surigao del Norte": {
        "cities": [
            "Alegria",
            "Bacuag",
            "Burgos",
            "Claver",
            "Dapa",
            "Del Carmen",
            "General Luna",
            "Gigaquit",
            "Mainit",
            "Malimono",
            "Pilar",
            "Placer",
            "San Benito",
            "San Francisco",
            "San Isidro",
            "Santa Monica",
            "Sison",
            "Socorro",
            "Surigao City",
            "Tagana-an",
            "Tubod"
        ]
    },
    "Surigao del Sur": {
        "cities": [
            "Barobo",
            "Bayabas",
            "Bislig",
            "Cagwait",
            "Cantilan",
            "Carmen",
            "Carrascal",
            "Cortes",
            "Hinatuan",
            "Lanuza",
            "Lianga",
            "Lingig",
            "Madrid",
            "Marihatag",
            "San Agustin",
            "San Miguel",
            "Tagbina",
            "Tago",
            "Tandag"
        ]
    },
    "Tarlac": {
        "cities": [
            "Anao",
            "Bamban",
            "Camiling",
            "Capas",
            "Concepcion",
            "Gerona",
            "La Paz",
            "Mayantoc",
            "Moncada",
            "Paniqui",
            "Pura",
            "Ramos",
            "San Clemente",
            "San Jose",
            "San Manuel",
            "Santa Ignacia",
            "Tarlac City",
            "Victoria"
        ]
    },
    "Tawi-Tawi": {
        "cities": [
            "Bongao",
            "Languyan",
            "Mapun",
            "Panglima Sugala",
            "Sapa-Sapa",
            "Sibutu",
            "Simunul",
            "Sitangkai",
            "South Ubian",
            "Tandubas",
            "Turtle Islands"
        ]
    },
    "Zambales": {
        "cities": [
            "Botolan",
            "Cabangan",
            "Candelaria",
            "Castillejos",
            "Iba",
            "Masinloc",
            "Palauig",
            "San Antonio",
            "San Felipe",
            "San Marcelino",
            "San Narciso",
            "Santa Cruz",
            "Subic"
        ]
    },
    "Zamboanga del Norte": {
        "cities": [
            "Baliguian",
            "Dapitan",
            "Dipolog",
            "Godod",
            "Gutalac",
            "Jose Dalman",
            "Kalawit",
            "Katipunan",
            "La Libertad",
            "Labason",
            "Leon B. Postigo",
            "Liloy",
            "Manukan",
            "Mutia",
            "Piñan",
            "Polanco",
            "President Manuel A. Roxas",
            "Rizal",
            "Salug",
            "Sergio Osmeña Sr.",
            "Siayan",
            "Sibuco",
            "Sibutad",
            "Sindangan",
            "Siocon",
            "Sirawai",
            "Tampilisan"
        ]
    },
    "Zamboanga del Sur": {
        "cities": [
            "Aurora",
            "Bayog",
            "Dimataling",
            "Dinas",
            "Dumalinao",
            "Dumingag",
            "Guipos",
            "Josefina",
            "Kumalarang",
            "Labangan",
            "Lakewood",
            "Lapuyan",
            "Mahayag",
            "Margosatubig",
            "Midsalip",
            "Molave",
            "Pagadian",
            "Pitogo",
            "Ramon Magsaysay",
            "San Miguel",
            "San Pablo",
            "Sominot",
            "Tabina",
            "Tambulig",
            "Tigbao",
            "Tukuran",
            "Vincenzo A. Sagun"
        ]
    },
    "Zamboanga Sibugay": {
        "cities": [
            "Alicia",
            "Buug",
            "Diplahan",
            "Imelda",
            "Ipil"
        ]
    }
};

// Function to populate the dropdown
function populatePlaceOfBirth() {
    const $placeOfBirth = $('#place-of-birth');

    // Clear existing options
    $placeOfBirth.empty().append('<option value="">Select Place of Birth</option>');

    // Populate options from the provinces object
    for (const province in provinces) {
        if (provinces.hasOwnProperty(province)) {
            provinces[province].cities.forEach(city => {
                const optionValue = `${city}, ${province}`;
                $placeOfBirth.append(new Option(optionValue, optionValue));
            });
        }
    }

    // Initialize Select2
    $placeOfBirth.select2({
        placeholder: "Select Place of Birth",
        allowClear: true
    });
}

// Call the function to populate the dropdown
$(document).ready(function() {
    populatePlaceOfBirth();
});